{% set name = "PySDL2" %}
{% set version = "0.9.17" %}
{% set md5 = "8dd193d3b01d949b256b5bb95c277dc6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.lower() }}-{{ version }}.tar.gz
  md5: {{ md5 }}
  patches:
    - no_sdl2dll.patch

build:
  script_env:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=dummy
    - SDL_RENDER_DRIVER=software
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - sdl2
    - python

test:
  requires:
    - pytest
    - sdl2_ttf
    - sdl2_mixer
    # tests on Windows are broken
    - sdl2_image  # [not win]
    - sdl2_gfx
    - numpy
    - pillow
    - sdl2
  commands:
    - python -m pytest --pyargs sdl2.test -vvl -rxXP  # [python_impl != 'pypy']

about:
  home: https://github.com/marcusva/py-sdl2
  license: CC0-1.0
  license_file: doc/copying.rst
  summary: A wrapper around the SDL2 library
  description: |
    PySDL2 is a wrapper around the SDL2 library and as such similar to the
    discontinued PySDL project. In contrast to PySDL, it has no licensing
    restrictions, nor does it rely on C code, but uses ctypes instead.
  doc_url: https://pysdl2.readthedocs.io
  dev_url: https://bitbucket.org/marcusva/py-sdl2

extra:
  recipe-maintainers:
    - dschreij
    - a-hurst
    - Tobias-Fischer
