{% set name = "PySDL2" %}
{% set version = "0.9.12" %}
{% set md5 = "a00677d6cecbddc919c60ae1ccea8e2e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}
  patches:
    - no_sdl2dll.patch

build:
  script_env:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=dummy
    - SDL_RENDER_DRIVER=software
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - sdl2
    - python

test:
  requires:
    - pytest
    - sdl2_ttf
    - sdl2_mixer
#   - sdl2_image  # waiting on conda-forge SDL2_image fixes
    - sdl2_gfx
    - numpy
    - pillow
    - sdl2
  commands:
    - python -m pytest --pyargs sdl2.test -vvl -rxXP

about:
  home: https://github.com/marcusva/py-sdl2
  license: CC0-1.0
  license_file: doc/copying.rst
  summary: A wrapper around the SDL2 library
  description: |
    PySDL2 is a wrapper around the SDL2 library and as such similar to the
    discontinued PySDL project. In contrast to PySDL, it has no licensing
    restrictions, nor does it rely on C code, but uses ctypes instead.
  doc_url: https://pysdl2.readthedocs.io
  dev_url: https://bitbucket.org/marcusva/py-sdl2

extra:
  recipe-maintainers:
    - dschreij
    - a-hurst
