{% set name = "PySDL2" %}
{% set version = "0.9.10" %}
{% set md5 = "98ebe1b7a657614c38b6805dc1df9b59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - sdl2
    - python

test:
  requires:
    - pytest
    - sdl2_ttf
    - sdl2_mixer
    - sdl2_image
    - sdl2_gfx
    - numpy
    - pillow
  source_files:
    - pytest.ini
    - sdl2/test
    - sdl2/test/resources/*
    - sdl2/test/*.py
  imports:
    - sdl2
  commands:
    - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy SDL_RENDER_DRIVER=software python -m pytest -vvl -rxXP

about:
  home: https://github.com/marcusva/py-sdl2
  license: CC0-1.0
  license_file: doc/copying.rst
  summary: A wrapper around the SDL2 library
  description: |
    PySDL2 is a wrapper around the SDL2 library and as such similar to the
    discontinued PySDL project. In contrast to PySDL, it has no licensing
    restrictions, nor does it rely on C code, but uses ctypes instead.
  doc_url: https://pysdl2.readthedocs.io
  dev_url: https://bitbucket.org/marcusva/py-sdl2

extra:
  recipe-maintainers:
    - dschreij
